apiVersion: apps/v1
kind: Deployment
metadata: 
  name: db-dep
  labels:
    app: thesis-app
    tier: db
spec:
  selector:
    matchLabels:
      app: thesis-app
      tier: db
  template:
    metadata:
      labels:
        app: thesis-app
        tier: db
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb
          ports:
            - name: http
              containerPort: 3306
