apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels: 
    app: thesis-app
    tier: frontend
spec:
  selector:
    app: thesis-app
    tier: frontend
  ports:
  - protocol: TCP
    port: 0
    targetPort: 80
  type: LoadBalancer
