apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: backend
  newName: mattedamo26/thesis-demo-backend
  newTag: a734a6a2d917df8e94a5111129b0f92dde76d4a8-releases-r1
- name: frontend
  newName: mattedamo26/thesis-demo-frontend
  newTag: latest-prod
kind: Kustomization
namespace: thesis-demo-backend-releases-r1
patches:
- path: backend_backend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-dep
- path: backend_backend-service_service_patch.yaml
  target:
    labelSelector: tier=backend
    name: backend-service
- path: frontend_frontend-dep_deployment_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend-dep
- path: frontend_frontend-service_service_patch.yaml
  target:
    labelSelector: tier=frontend
    name: frontend-service
- path: db_db-dep_deployment_patch.yaml
  target:
    labelSelector: tier=db
    name: db-dep
resources:
- ../../../../base
secretGenerator:
- literals:
  - MYSQL_ROOT_PASSWORD=password
  - MYSQL_DATABASE=thesisAppMariadb
  name: db-db-dep
